### ISSUE TITLE
bounds.txt format

### ISSUE THREAD

**Issue by rasanderson** [ghuertaramos/Inat_Images#10]
I don't think you need the c( ) around the bounding box coordinates, otherwise it seems to corrupt the search area and gives incorrect results.

**Comment by ghuertaramos** [comment]
Hi Roy,
Thank you for pointing out the issue! I've implemented a fix to ensure the script correctly handles the c() syntax for bounding box coordinates. Please let me know if the problem persists.
Best regards.

**Comment by rasanderson** [comment]
Thank you. Really useful utility script.
