### ISSUE TITLE
inat_images.R does not work.

### ISSUE THREAD

**Issue by madbadfake** [ghuertaramos/Inat_Images#6]
Hey there,
im not sure if i did something wrong, but i cant use the command as in the readme. RStudio doesnt seem to recognize it.

if i try
Rscript inat_images.R -o 2000 -q All_Q -l Wikicommons
i get "unexpected symbol in  "Rscript inat_images.R"

Somehow it still downloaded like 1-3 pictures for some, and created folders for all species of the genus, even those which i didnt enter.

**Comment by ghuertaramos** [comment]
Hi @madbadfake ! Are you able to use the sample csv file? I think it may be related to your list. Would you mind sharing it privately to ghuertaramos@gmail.com. Also, Rstudio is not necessary to run the script.

**Comment by ghuertaramos** [comment]
The input file was not read correctly, since @madbadfake csv file had ";" symbols as separators instead of ","
